[root]
key = "C-r"

[root.keys]
C-v = "paste-buffer"
C-M-r = "new-window 'vim ~/.tmux.conf'"
C-M-m = "new-window 'vim ~/.modes.toml'"

[session]
key = "M-s"

[session.keys]
x = '''set-option key-table root \; split-window -h "tmux list-sessions | fzf -m --reverse | sed -n 's/:.*$//p' | xargs -I session_id tmux kill-session -t session_id"'''
M-s = '''set-option key-table root \; split-window -h "tmux list-sessions | fzf --reverse | sed -n 's/:.*$//p' | xargs tmux switch-client -t"'''
n = '''set-option key-table root \; new-session'''

[window]
key = "C-w"

[window.keys]
+ = "new-window -a"
- = "kill-window"
x = "kill-pane"
h = "split-window -h"
H = "split-window -bh"
v = "split-window -v"
V = "split-window -bv"
Left = "select-pane -L"
Up = "select-pane -U"
Down = "select-pane -D"
Right = "select-pane -R"
C-Left = "resize-pane -L"
C-Up = "resize-pane -U"
C-Down = "resize-pane -D"
C-Right = "resize-pane -R"
a = "select-window -p"
d = "select-window -n"
s = "select-window -l"

[scroll]
key = "C-s"
copy = true

[scroll.keys]
s = "command-prompt -i -p '(search down)' -I '#{pane_search_string}' \"send-keys -X search-forward-incremental \"%%\"\""
S = "command-prompt -i -p '(search up)' -I '#{pane_search_string}' \"send-keys -X search-backward-incremental \"%%\"\""

[scroll.copykeys]
C-Up = "scroll-up"
C-Down = "scroll-down"
Up = "cursor-up"
Down = "cursor-down"
Left = "cursor-left"
Right = "cursor-right"
Space = "begin-selection"
Enter = "copy-selection-and-cancel"
C-c = "copy-selection-and-cancel"
Escape = "clear-selection"
PageUp = "page-up"
PageDown = "page-down"
Home = "start-of-line"
End = "end-of-line"
n = "search-again"
N = "search-reverse"

[vim]
key="M-v"
unkeys = ["C-c", "C-x", "C-v", "C-w", "M-r"]
